In [2]:
import yfinance as yf

msft = yf.Ticker("MSFT")

In [ ]:
# get all stock info
msft.info

In [57]:
# get historical market data
hist = msft.history(period="1mo")
hist

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2024-07-09 00:00:00-04:00,467.000000,467.329987,458.000000,459.540009,17207200,0.0,0.0
2024-07-10 00:00:00-04:00,461.220001,466.459991,458.859985,466.250000,18196100,0.0,0.0
2024-07-11 00:00:00-04:00,462.980011,464.779999,451.549988,454.700012,23111200,0.0,0.0
2024-07-12 00:00:00-04:00,454.329987,456.359985,450.649994,453.549988,16324300,0.0,0.0
2024-07-15 00:00:00-04:00,453.299988,457.260010,451.429993,453.959991,14429400,0.0,0.0
2024-07-16 00:00:00-04:00,454.220001,454.299988,446.660004,449.519989,17175700,0.0,0.0
2024-07-17 00:00:00-04:00,442.589996,444.850006,439.179993,443.519989,21778000,0.0,0.0
2024-07-18 00:00:00-04:00,444.339996,444.649994,434.399994,440.369995,20794800,0.0,0.0
2024-07-19 00:00:00-04:00,433.100006,441.140015,432.000000,437.109985,20940400,0.0,0.0
2024-07-22 00:00:00-04:00,441.790009,444.600006,438.910004,442.940002,15808800,0.0,0.0
2024-07-23 00:00:00-04:00,443.899994,448.390015,443.100006,444.850006,13107100,0.0,0.0
2024-07-24 00:00:00-04:00,440.450012,441.480011,427.589996,428.899994,26805800,0.0,0.0
2024-07-25 00:00:00-04:00,428.799988,429.799988,417.510010,418.399994,29943800,0.0,0.0
2024-07-26 00:00:00-04:00,418.200012,428.920013,417.269989,425.269989,23583800,0.0,0.0
2024-07-29 00:00:00-04:00,431.579987,432.149994,424.700012,426.730011,15125800,0.0,0.0
2024-07-30 00:00:00-04:00,427.720001,429.049988,417.359985,422.920013,32687600,0.0,0.0
2024-07-31 00:00:00-04:00,420.500000,421.779999,412.209991,418.350006,42891400,0.0,0.0
2024-08-01 00:00:00-04:00,420.790009,427.459991,413.089996,417.109985,30296400,0.0,0.0
2024-08-02 00:00:00-04:00,412.489990,415.000000,404.339996,408.489990,29437900,0.0,0.0
2024-08-05 00:00:00-04:00,389.170013,401.040009,385.579987,395.149994,40709200,0.0,0.0
2024-08-06 00:00:00-04:00,400.000000,405.670013,398.500000,399.609985,24946500,0.0,0.0
2024-08-07 00:00:00-04:00,408.640015,410.079987,397.470001,398.429993,20650900,0.0,0.0
2024-08-08 00:00:00-04:00,402.440002,405.859985,399.940002,402.690002,18649900,0.0,0.0

In [58]:
hist.to_dict(orient='index')

{Timestamp('2024-07-09 00:00:00-0400', tz='America/New_York'): {'Open': 467.0,
  'High': 467.3299865722656,
  'Low': 458.0,
  'Close': 459.5400085449219,
  'Volume': 17207200,
  'Dividends': 0.0,
  'Stock Splits': 0.0},
 Timestamp('2024-07-10 00:00:00-0400', tz='America/New_York'): {'Open': 461.2200012207031,
  'High': 466.4599914550781,
  'Low': 458.8599853515625,
  'Close': 466.25,
  'Volume': 18196100,
  'Dividends': 0.0,
  'Stock Splits': 0.0},
 Timestamp('2024-07-11 00:00:00-0400', tz='America/New_York'): {'Open': 462.9800109863281,
  'High': 464.7799987792969,
  'Low': 451.54998779296875,
  'Close': 454.70001220703125,
  'Volume': 23111200,
  'Dividends': 0.0,
  'Stock Splits': 0.0},
 Timestamp('2024-07-12 00:00:00-0400', tz='America/New_York'): {'Open': 454.3299865722656,
  'High': 456.3599853515625,
  'Low': 450.6499938964844,
  'Close': 453.54998779296875,
  'Volume': 16324300,
  'Dividends': 0.0,
  'Stock Splits': 0.0},
 Timestamp('2024-07-15 00:00:00-0400', tz='America/New_York'): {'Open': 453.29998779296875,
  'High': 457.260009765625,
  'Low': 451.42999267578125,
  'Close': 453.9599914550781,
  'Volume': 14429400,
  'Dividends': 0.0,
  'Stock Splits': 0.0},
 Timestamp('2024-07-16 00:00:00-0400', tz='America/New_York'): {'Open': 454.2200012207031,
  'High': 454.29998779296875,
  'Low': 446.6600036621094,
  'Close': 449.5199890136719,
  'Volume': 17175700,
  'Dividends': 0.0,
  'Stock Splits': 0.0},
 Timestamp('2024-07-17 00:00:00-0400', tz='America/New_York'): {'Open': 442.5899963378906,
  'High': 444.8500061035156,
  'Low': 439.17999267578125,
  'Close': 443.5199890136719,
  'Volume': 21778000,
  'Dividends': 0.0,
  'Stock Splits': 0.0},
 Timestamp('2024-07-18 00:00:00-0400', tz='America/New_York'): {'Open': 444.3399963378906,
  'High': 444.6499938964844,
  'Low': 434.3999938964844,
  'Close': 440.3699951171875,
  'Volume': 20794800,
  'Dividends': 0.0,
  'Stock Splits': 0.0},
 Timestamp('2024-07-19 00:00:00-0400', tz='America/New_York'): {'Open': 433.1000061035156,
  'High': 441.1400146484375,
  'Low': 432.0,
  'Close': 437.1099853515625,
  'Volume': 20940400,
  'Dividends': 0.0,
  'Stock Splits': 0.0},
 Timestamp('2024-07-22 00:00:00-0400', tz='America/New_York'): {'Open': 441.7900085449219,
  'High': 444.6000061035156,
  'Low': 438.9100036621094,
  'Close': 442.94000244140625,
  'Volume': 15808800,
  'Dividends': 0.0,
  'Stock Splits': 0.0},
 Timestamp('2024-07-23 00:00:00-0400', tz='America/New_York'): {'Open': 443.8999938964844,
  'High': 448.3900146484375,
  'Low': 443.1000061035156,
  'Close': 444.8500061035156,
  'Volume': 13107100,
  'Dividends': 0.0,
  'Stock Splits': 0.0},
 Timestamp('2024-07-24 00:00:00-0400', tz='America/New_York'): {'Open': 440.45001220703125,
  'High': 441.4800109863281,
  'Low': 427.5899963378906,
  'Close': 428.8999938964844,
  'Volume': 26805800,
  'Dividends': 0.0,
  'Stock Splits': 0.0},
 Timestamp('2024-07-25 00:00:00-0400', tz='America/New_York'): {'Open': 428.79998779296875,
  'High': 429.79998779296875,
  'Low': 417.510009765625,
  'Close': 418.3999938964844,
  'Volume': 29943800,
  'Dividends': 0.0,
  'Stock Splits': 0.0},
 Timestamp('2024-07-26 00:00:00-0400', tz='America/New_York'): {'Open': 418.20001220703125,
  'High': 428.9200134277344,
  'Low': 417.2699890136719,
  'Close': 425.2699890136719,
  'Volume': 23583800,
  'Dividends': 0.0,
  'Stock Splits': 0.0},
 Timestamp('2024-07-29 00:00:00-0400', tz='America/New_York'): {'Open': 431.5799865722656,
  'High': 432.1499938964844,
  'Low': 424.70001220703125,
  'Close': 426.7300109863281,
  'Volume': 15125800,
  'Dividends': 0.0,
  'Stock Splits': 0.0},
 Timestamp('2024-07-30 00:00:00-0400', tz='America/New_York'): {'Open': 427.7200012207031,
  'High': 429.04998779296875,
  'Low': 417.3599853515625,
  'Close': 422.9200134277344,
  'Volume': 32687600,
  'Dividends': 0.0,
  'Stock Splits': 0.0},
 Timestamp('2024-07-31 00:00:00-0400', tz='America/New_York'): {'Open': 420.5,
  'High': 421.7799987792969,
  'Low': 412.2099914550781,
  'Close': 418.3500061035156,
  'Volume': 42891400,
  'Dividends': 0.0,
  'Stock Splits': 0.0},
 Timestamp('2024-08-01 00:00:00-0400', tz='America/New_York'): {'Open': 420.7900085449219,
  'High': 427.4599914550781,
  'Low': 413.0899963378906,
  'Close': 417.1099853515625,
  'Volume': 30296400,
  'Dividends': 0.0,
  'Stock Splits': 0.0},
 Timestamp('2024-08-02 00:00:00-0400', tz='America/New_York'): {'Open': 412.489990234375,
  'High': 415.0,
  'Low': 404.3399963378906,
  'Close': 408.489990234375,
  'Volume': 29437900,
  'Dividends': 0.0,
  'Stock Splits': 0.0},
 Timestamp('2024-08-05 00:00:00-0400', tz='America/New_York'): {'Open': 389.1700134277344,
  'High': 401.0400085449219,
  'Low': 385.5799865722656,
  'Close': 395.1499938964844,
  'Volume': 40709200,
  'Dividends': 0.0,
  'Stock Splits': 0.0},
 Timestamp('2024-08-06 00:00:00-0400', tz='America/New_York'): {'Open': 400.0,
  'High': 405.6700134277344,
  'Low': 398.5,
  'Close': 399.6099853515625,
  'Volume': 24946500,
  'Dividends': 0.0,
  'Stock Splits': 0.0},
 Timestamp('2024-08-07 00:00:00-0400', tz='America/New_York'): {'Open': 408.6400146484375,
  'High': 410.0799865722656,
  'Low': 397.4700012207031,
  'Close': 398.42999267578125,
  'Volume': 20650900,
  'Dividends': 0.0,
  'Stock Splits': 0.0},
 Timestamp('2024-08-08 00:00:00-0400', tz='America/New_York'): {'Open': 402.44000244140625,
  'High': 405.8599853515625,
  'Low': 399.94000244140625,
  'Close': 402.69000244140625,
  'Volume': 18649900,
  'Dividends': 0.0,
  'Stock Splits': 0.0}}

In [5]:
msft.history_metadata

{'currency': 'USD',
 'symbol': 'MSFT',
 'exchangeName': 'NMS',
 'fullExchangeName': 'NasdaqGS',
 'instrumentType': 'EQUITY',
 'firstTradeDate': 511108200,
 'regularMarketTime': 1723147201,
 'hasPrePostMarketData': True,
 'gmtoffset': -14400,
 'timezone': 'EDT',
 'exchangeTimezoneName': 'America/New_York',
 'regularMarketPrice': 402.69,
 'fiftyTwoWeekHigh': 405.86,
 'fiftyTwoWeekLow': 399.941,
 'regularMarketDayHigh': 405.86,
 'regularMarketDayLow': 399.941,
 'regularMarketVolume': 19197742,
 'chartPreviousClose': 466.24,
 'priceHint': 2,
 'currentTradingPeriod': {'pre': {'timezone': 'EDT',
   'start': 1723104000,
   'end': 1723123800,
   'gmtoffset': -14400},
  'regular': {'timezone': 'EDT',
   'start': 1723123800,
   'end': 1723147200,
   'gmtoffset': -14400},
  'post': {'timezone': 'EDT',
   'start': 1723147200,
   'end': 1723161600,
   'gmtoffset': -14400}},
 'dataGranularity': '1d',
 'range': '1mo',
 'validRanges': ['1d',
  '5d',
  '1mo',
  '3mo',
  '6mo',
  '1y',
  '2y',
  '5y',
  '10y',
  'ytd',
  'max']}

In [10]:
msft.actions

Empty DataFrame
Columns: [Dividends, Stock Splits]
Index: []

In [11]:
msft.dividends

Series([], Name: Dividends, dtype: float64)

In [12]:
msft.splits

Series([], Name: Stock Splits, dtype: float64)

In [13]:
msft.capital_gains

Series([], dtype: object)

In [15]:
# show share count
msft.get_shares_full(start=None, end=None)

2023-03-08 00:00:00-05:00    7523469824
2023-03-08 00:00:00-05:00    7443800064
2023-03-10 00:00:00-05:00    7443800064
2023-03-10 00:00:00-05:00    7484519936
2023-03-30 00:00:00-04:00    7586610176
                                ...
2024-07-31 00:00:00-04:00    7432309760
2024-08-01 00:00:00-04:00    7433039872
2024-08-02 00:00:00-04:00    7433039872
2024-08-06 00:00:00-04:00    7433039872
2024-08-07 00:00:00-04:00    7433039872
Length: 191, dtype: int64

##### show financials:

In [24]:

# - income statement
print(msft.income_stmt)
# print(msft.quarterly_income_stmt)

                                                        2024-06-30  \
Tax Effect Of Unusual Items                            -99918000.0
Tax Rate For Calcs                                           0.182
Normalized EBITDA                                   133558000000.0
Total Unusual Items                                   -549000000.0
Total Unusual Items Excluding Goodwill                -549000000.0
Net Income From Continuing Operation Net Minori...   88136000000.0
Reconciled Depreciation                              22287000000.0
Reconciled Cost Of Revenue                           74114000000.0
EBITDA                                              133009000000.0
EBIT                                                110722000000.0
Net Interest Income                                    222000000.0
Interest Expense                                      2935000000.0
Interest Income                                       3157000000.0
Normalized Income                                    88585082000.0
Net Income From Continuing And Discontinued Ope...   88136000000.0
Total Expenses                                      135689000000.0
Total Operating Income As Reported                  109433000000.0
Diluted Average Shares                                7469000000.0
Basic Average Shares                                  7431000000.0
Diluted EPS                                                   11.8
Basic EPS                                                    11.86
Diluted NI Availto Com Stockholders                  88136000000.0
Net Income Common Stockholders                       88136000000.0
Net Income                                           88136000000.0
Net Income Including Noncontrolling Interests        88136000000.0
Net Income Continuous Operations                     88136000000.0
Tax Provision                                        19651000000.0
Pretax Income                                       107787000000.0
Other Income Expense                                 -1868000000.0
Other Non Operating Income Expenses                  -1319000000.0
Special Income Charges                                -206000000.0
Write Off                                              206000000.0
Gain On Sale Of Security                              -343000000.0
Net Non Operating Interest Income Expense              222000000.0
Interest Expense Non Operating                        2935000000.0
Interest Income Non Operating                         3157000000.0
Operating Income                                    109433000000.0
Operating Expense                                    61575000000.0
Research And Development                             29510000000.0
Selling General And Administration                   32065000000.0
Selling And Marketing Expense                        24456000000.0
General And Administrative Expense                    7609000000.0
Other Gand A                                          7609000000.0
Gross Profit                                        171008000000.0
Cost Of Revenue                                      74114000000.0
Total Revenue                                       245122000000.0
Operating Revenue                                   245122000000.0

                                                        2023-06-30  \
Tax Effect Of Unusual Items                             -2850000.0
Tax Rate For Calcs                                            0.19
Normalized EBITDA                                   105155000000.0
Total Unusual Items                                    -15000000.0
Total Unusual Items Excluding Goodwill                 -15000000.0
Net Income From Continuing Operation Net Minori...   72361000000.0
Reconciled Depreciation                              13861000000.0
Reconciled Cost Of Revenue                           65863000000.0
EBITDA                                              105140000000.0
EBIT                                                 91279000000.0
Net Interest Income                                   1026000000.0
Interest Expense                                      1968000000.0
Interest Income                                       2994000000.0
Normalized Income                                    72373150000.0
Net Income From Continuing And Discontinued Ope...   72361000000.0
Total Expenses                                      123392000000.0
Total Operating Income As Reported                   88523000000.0
Diluted Average Shares                                7472000000.0
Basic Average Shares                                  7446000000.0
Diluted EPS                                                   9.68
Basic EPS                                                     9.72
Diluted NI Availto Com Stockholders                  72361000000.0
Net Income Common Stockholders                       72361000000.0
Net Income                                           72361000000.0
Net Income Including Noncontrolling Interests        72361000000.0
Net Income Continuous Operations                     72361000000.0
Tax Provision                                        16950000000.0
Pretax Income                                        89311000000.0
Other Income Expense                                  -238000000.0
Other Non Operating Income Expenses                   -223000000.0
Special Income Charges                                 -30000000.0
Write Off                                               30000000.0
Gain On Sale Of Security                                15000000.0
Net Non Operating Interest Income Expense             1026000000.0
Interest Expense Non Operating                        1968000000.0
Interest Income Non Operating                         2994000000.0
Operating Income                                     88523000000.0
Operating Expense                                    57529000000.0
Research And Development                             27195000000.0
Selling General And Administration                   30334000000.0
Selling And Marketing Expense                        22759000000.0
General And Administrative Expense                    7575000000.0
Other Gand A                                          7575000000.0
Gross Profit                                        146052000000.0
Cost Of Revenue                                      65863000000.0
Total Revenue                                       211915000000.0
Operating Revenue                                   211915000000.0

                                                        2022-06-30  \
Tax Effect Of Unusual Items                             43754000.0
Tax Rate For Calcs                                           0.131
Normalized EBITDA                                    99905000000.0
Total Unusual Items                                    334000000.0
Total Unusual Items Excluding Goodwill                 334000000.0
Net Income From Continuing Operation Net Minori...   72738000000.0
Reconciled Depreciation                              14460000000.0
Reconciled Cost Of Revenue                           62650000000.0
EBITDA                                              100239000000.0
EBIT                                                 85779000000.0
Net Interest Income                                     31000000.0
Interest Expense                                      2063000000.0
Interest Income                                       2094000000.0
Normalized Income                                    72447754000.0
Net Income From Continuing And Discontinued Ope...   72738000000.0
Total Expenses                                      114887000000.0
Total Operating Income As Reported                   83383000000.0
Diluted Average Shares                                7540000000.0
Basic Average Shares                                  7496000000.0
Diluted EPS                                                   9.65
Basic EPS                                                      9.7
Diluted NI Availto Com Stockholders                  72738000000.0
Net Income Common Stockholders                       72738000000.0
Net Income                                           72738000000.0
Net Income Including Noncontrolling Interests        72738000000.0
Net Income Continuous Operations                     72738000000.0
Tax Provision                                        10978000000.0
Pretax Income                                        83716000000.0
Other Income Expense                                   302000000.0
Other Non Operating Income Expenses                    -32000000.0
Special Income Charges                                -101000000.0
Write Off                                              101000000.0
Gain On Sale Of Security                               435000000.0
Net Non Operating Interest Income Expense               31000000.0
Interest Expense Non Operating                        2063000000.0
Interest Income Non Operating                         2094000000.0
Operating Income                                     83383000000.0
Operating Expense                                    52237000000.0
Research And Development                             24512000000.0
Selling General And Administration                   27725000000.0
Selling And Marketing Expense                        21825000000.0
General And Administrative Expense                    5900000000.0
Other Gand A                                          5900000000.0
Gross Profit                                        135620000000.0
Cost Of Revenue                                      62650000000.0
Total Revenue                                       198270000000.0
Operating Revenue                                   198270000000.0

                                                            2021-06-30
Tax Effect Of Unusual Items                           180160797.164637
Tax Rate For Calcs                                            0.138266
Normalized EBITDA                                        83831000000.0
Total Unusual Items                                       1303000000.0
Total Unusual Items Excluding Goodwill                    1303000000.0
Net Income From Continuing Operation Net Minori...       61271000000.0
Reconciled Depreciation                                  11686000000.0
Reconciled Cost Of Revenue                               52232000000.0
EBITDA                                                   85134000000.0
EBIT                                                     73448000000.0
Net Interest Income                                       -215000000.0
Interest Expense                                          2346000000.0
Interest Income                                           2131000000.0
Normalized Income                                   60148160797.164635
Net Income From Continuing And Discontinued Ope...       61271000000.0
Total Expenses                                           98172000000.0
Total Operating Income As Reported                       69916000000.0
Diluted Average Shares                                    7608000000.0
Basic Average Shares                                      7547000000.0
Diluted EPS                                                       8.05
Basic EPS                                                         8.12
Diluted NI Availto Com Stockholders                      61271000000.0
Net Income Common Stockholders                           61271000000.0
Net Income                                               61271000000.0
Net Income Including Noncontrolling Interests            61271000000.0
Net Income Continuous Operations                         61271000000.0
Tax Provision                                             9831000000.0
Pretax Income                                            71102000000.0
Other Income Expense                                      1401000000.0
Other Non Operating Income Expenses                         98000000.0
Special Income Charges                                     -13000000.0
Write Off                                                   13000000.0
Gain On Sale Of Security                                  1316000000.0
Net Non Operating Interest Income Expense                 -215000000.0
Interest Expense Non Operating                            2346000000.0
Interest Income Non Operating                             2131000000.0
Operating Income                                         69916000000.0
Operating Expense                                        45940000000.0
Research And Development                                 20716000000.0
Selling General And Administration                       25224000000.0
Selling And Marketing Expense                            20117000000.0
General And Administrative Expense                        5107000000.0
Other Gand A                                              5107000000.0
Gross Profit                                            115856000000.0
Cost Of Revenue                                          52232000000.0
Total Revenue                                           168088000000.0
Operating Revenue                                       168088000000.0

In [23]:
# - balance sheet
print(msft.balance_sheet)
# print(msft.quarterly_balance_sheet)

                                                      2024-06-30  \
Ordinary Shares Number                              7434000000.0
Share Issued                                        7434000000.0
Net Debt                                           33315000000.0
Total Debt                                         67127000000.0
Tangible Book Value                               121660000000.0
...                                                          ...
Cash Cash Equivalents And Short Term Investments   75531000000.0
Other Short Term Investments                       57216000000.0
Cash And Cash Equivalents                          18315000000.0
Cash Equivalents                                    6744000000.0
Cash Financial                                     11571000000.0

                                                      2023-06-30  \
Ordinary Shares Number                              7432000000.0
Share Issued                                        7432000000.0
Net Debt                                           12533000000.0
Total Debt                                         59965000000.0
Tangible Book Value                               128971000000.0
...                                                          ...
Cash Cash Equivalents And Short Term Investments  111256000000.0
Other Short Term Investments                       76552000000.0
Cash And Cash Equivalents                          34704000000.0
Cash Equivalents                                   26226000000.0
Cash Financial                                      8478000000.0

                                                      2022-06-30  \
Ordinary Shares Number                              7464000000.0
Share Issued                                        7464000000.0
Net Debt                                           35850000000.0
Total Debt                                         61270000000.0
Tangible Book Value                                87720000000.0
...                                                          ...
Cash Cash Equivalents And Short Term Investments  104749000000.0
Other Short Term Investments                       90818000000.0
Cash And Cash Equivalents                          13931000000.0
Cash Equivalents                                    5673000000.0
Cash Financial                                      8258000000.0

                                                      2021-06-30
Ordinary Shares Number                              7519000000.0
Share Issued                                        7519000000.0
Net Debt                                           43922000000.0
Total Debt                                         67775000000.0
Tangible Book Value                                84477000000.0
...                                                          ...
Cash Cash Equivalents And Short Term Investments  130256000000.0
Other Short Term Investments                      116032000000.0
Cash And Cash Equivalents                          14224000000.0
Cash Equivalents                                    6952000000.0
Cash Financial                                      7272000000.0

[73 rows x 4 columns]

In [27]:
# - cash flow statement
print(msft.cashflow)
# print(msft.quarterly_cashflow)

                                                   2024-06-30     2024-03-31  \
Free Cash Flow                                  23322000000.0  20965000000.0
Repurchase Of Capital Stock                     -4210000000.0  -4213000000.0
Repayment Of Debt                              -13065000000.0 -11589000000.0
Issuance Of Debt                                 5447000000.0   6352000000.0
Issuance Of Capital Stock                         534000000.0    522000000.0
Capital Expenditure                            -13873000000.0 -10952000000.0
End Cash Position                               18315000000.0  19634000000.0
Beginning Cash Position                         19634000000.0  17305000000.0
Effect Of Exchange Rate Changes                  -103000000.0    -80000000.0
Changes In Cash                                 -1216000000.0   2409000000.0
Financing Cash Flow                            -23563000000.0 -18808000000.0
Cash Flow From Continuing Financing Activities -23563000000.0 -18808000000.0
Net Other Financing Charges                      -303000000.0   -498000000.0
Cash Dividends Paid                             -5574000000.0  -5572000000.0
Common Stock Dividend Paid                      -5574000000.0  -5572000000.0
Net Common Stock Issuance                       -3676000000.0  -3691000000.0
Common Stock Payments                           -4210000000.0  -4213000000.0
Common Stock Issuance                             534000000.0    522000000.0
Net Issuance Payments Of Debt                  -14010000000.0  -9047000000.0
Net Short Term Debt Issuance                    -1142000000.0  -3810000000.0
Short Term Debt Issuance                                  NaN            NaN
Net Long Term Debt Issuance                    -12868000000.0  -5237000000.0
Long Term Debt Payments                        -13065000000.0 -11589000000.0
Long Term Debt Issuance                           197000000.0   6352000000.0
Investing Cash Flow                            -14848000000.0 -10700000000.0
Cash Flow From Continuing Investing Activities -14848000000.0 -10700000000.0
Net Other Investing Changes                      -382000000.0  -1281000000.0
Net Investment Purchase And Sale                  749000000.0   3108000000.0
Sale Of Investment                               3580000000.0   5291000000.0
Purchase Of Investment                          -2831000000.0  -2183000000.0
Net Business Purchase And Sale                  -1342000000.0  -1575000000.0
Purchase Of Business                            -1342000000.0  -1575000000.0
Net PPE Purchase And Sale                      -13873000000.0 -10952000000.0
Purchase Of PPE                                -13873000000.0 -10952000000.0
Operating Cash Flow                             37195000000.0  31917000000.0
Cash Flow From Continuing Operating Activities  37195000000.0  31917000000.0
Change In Working Capital                        7184000000.0   2522000000.0
Change In Other Working Capital                 13164000000.0   1977000000.0
Change In Other Current Liabilities              5088000000.0   2851000000.0
Change In Other Current Assets                  -3768000000.0  -1186000000.0
Change In Payables And Accrued Expense           5891000000.0    648000000.0
Change In Payable                                5891000000.0    648000000.0
Change In Account Payable                        4204000000.0    648000000.0
Change In Inventory                                55000000.0    260000000.0
Change In Receivables                          -13246000000.0  -2028000000.0
Changes In Account Receivables                 -13246000000.0  -2028000000.0
Stock Based Compensation                         2696000000.0   2703000000.0
Deferred Tax                                    -1145000000.0  -1323000000.0
Deferred Income Tax                             -1145000000.0  -1323000000.0
Depreciation Amortization Depletion              6380000000.0   6027000000.0
Depreciation And Amortization                    6380000000.0   6027000000.0
Depreciation                                     6380000000.0   6027000000.0
Operating Gains Losses                             44000000.0     49000000.0
Net Income From Continuing Operations           22036000000.0  21939000000.0

                                                   2023-12-31     2023-09-30  \
Free Cash Flow                                   9118000000.0  20666000000.0
Repurchase Of Capital Stock                     -4000000000.0  -4831000000.0
Repayment Of Debt                               -2916000000.0  -1500000000.0
Issuance Of Debt                                10773000000.0  25765000000.0
Issuance Of Capital Stock                         261000000.0    685000000.0
Capital Expenditure                             -9735000000.0  -9917000000.0
End Cash Position                               17305000000.0  80452000000.0
Beginning Cash Position                         80452000000.0  34704000000.0
Effect Of Exchange Rate Changes                    72000000.0    -99000000.0
Changes In Cash                                -63219000000.0  45847000000.0
Financing Cash Flow                            -10147000000.0  14761000000.0
Cash Flow From Continuing Financing Activities -10147000000.0  14761000000.0
Net Other Financing Charges                      -201000000.0   -307000000.0
Cash Dividends Paid                             -5574000000.0  -5051000000.0
Common Stock Dividend Paid                      -5574000000.0  -5051000000.0
Net Common Stock Issuance                       -3739000000.0  -4146000000.0
Common Stock Payments                           -4000000000.0  -4831000000.0
Common Stock Issuance                             261000000.0    685000000.0
Net Issuance Payments Of Debt                    -633000000.0  24265000000.0
Net Short Term Debt Issuance                    -8490000000.0  18692000000.0
Short Term Debt Issuance                                  NaN  18692000000.0
Net Long Term Debt Issuance                      7857000000.0   5573000000.0
Long Term Debt Payments                         -2916000000.0  -1500000000.0
Long Term Debt Issuance                         10773000000.0   7073000000.0
Investing Cash Flow                            -71925000000.0    503000000.0
Cash Flow From Continuing Investing Activities -71925000000.0    503000000.0
Net Other Investing Changes                      1347000000.0   -982000000.0
Net Investment Purchase And Sale                 1492000000.0  12588000000.0
Sale Of Investment                               5750000000.0  21048000000.0
Purchase Of Investment                          -4258000000.0  -8460000000.0
Net Business Purchase And Sale                 -65029000000.0  -1186000000.0
Purchase Of Business                           -65029000000.0  -1186000000.0
Net PPE Purchase And Sale                       -9735000000.0  -9917000000.0
Purchase Of PPE                                 -9735000000.0  -9917000000.0
Operating Cash Flow                             18853000000.0  30583000000.0
Cash Flow From Continuing Operating Activities  18853000000.0  30583000000.0
Change In Working Capital                      -10300000000.0   2418000000.0
Change In Other Working Capital                 -7092000000.0  -2701000000.0
Change In Other Current Liabilities              1492000000.0  -3815000000.0
Change In Other Current Assets                   -702000000.0  -2809000000.0
Change In Payables And Accrued Expense          -2521000000.0   1214000000.0
Change In Payable                               -2521000000.0   1214000000.0
Change In Account Payable                       -2521000000.0   1214000000.0
Change In Inventory                              1474000000.0   -505000000.0
Change In Receivables                           -2951000000.0  11034000000.0
Changes In Account Receivables                  -2951000000.0  11034000000.0
Stock Based Compensation                         2828000000.0   2507000000.0
Deferred Tax                                    -1702000000.0   -568000000.0
Deferred Income Tax                             -1702000000.0   -568000000.0
Depreciation Amortization Depletion              5959000000.0   3921000000.0
Depreciation And Amortization                    5959000000.0   3921000000.0
Depreciation                                     5959000000.0            NaN
Operating Gains Losses                            198000000.0     14000000.0
Net Income From Continuing Operations           21870000000.0  22291000000.0

                                                   2023-06-30    2023-03-31
Free Cash Flow                                  19827000000.0           NaN
Repurchase Of Capital Stock                     -5704000000.0           NaN
Repayment Of Debt                               -1000000000.0           NaN
Issuance Of Debt                                          NaN           0.0
Issuance Of Capital Stock                         512000000.0           NaN
Capital Expenditure                             -8943000000.0           NaN
End Cash Position                               34704000000.0           NaN
Beginning Cash Position                         26562000000.0           NaN
Effect Of Exchange Rate Changes                   -81000000.0           NaN
Changes In Cash                                  8223000000.0           NaN
Financing Cash Flow                            -11413000000.0           NaN
Cash Flow From Continuing Financing Activities -11413000000.0           NaN
Net Other Financing Charges                      -167000000.0           NaN
Cash Dividends Paid                             -5054000000.0           NaN
Common Stock Dividend Paid                      -5054000000.0           NaN
Net Common Stock Issuance                       -5192000000.0           NaN
Common Stock Payments                           -5704000000.0           NaN
Common Stock Issuance                             512000000.0           NaN
Net Issuance Payments Of Debt                   -1000000000.0           NaN
Net Short Term Debt Issuance                              NaN           0.0
Short Term Debt Issuance                                  NaN           NaN
Net Long Term Debt Issuance                     -1000000000.0           NaN
Long Term Debt Payments                         -1000000000.0           NaN
Long Term Debt Issuance                                   NaN           0.0
Investing Cash Flow                             -9134000000.0           NaN
Cash Flow From Continuing Investing Activities  -9134000000.0           NaN
Net Other Investing Changes                      -269000000.0           NaN
Net Investment Purchase And Sale                  419000000.0           NaN
Sale Of Investment                              12395000000.0           NaN
Purchase Of Investment                         -11976000000.0           NaN
Net Business Purchase And Sale                   -341000000.0           NaN
Purchase Of Business                             -341000000.0           NaN
Net PPE Purchase And Sale                       -8943000000.0           NaN
Purchase Of PPE                                 -8943000000.0           NaN
Operating Cash Flow                             28770000000.0           NaN
Cash Flow From Continuing Operating Activities  28770000000.0           NaN
Change In Working Capital                        4243000000.0           NaN
Change In Other Working Capital                 14905000000.0           NaN
Change In Other Current Liabilities              2864000000.0           NaN
Change In Other Current Assets                  -3967000000.0           NaN
Change In Payables And Accrued Expense           1311000000.0           NaN
Change In Payable                                1311000000.0           NaN
Change In Account Payable                        1311000000.0           NaN
Change In Inventory                               374000000.0           NaN
Change In Receivables                          -11244000000.0           NaN
Changes In Account Receivables                 -11244000000.0           NaN
Stock Based Compensation                         2416000000.0           NaN
Deferred Tax                                    -1888000000.0           NaN
Deferred Income Tax                             -1888000000.0           NaN
Depreciation Amortization Depletion              3874000000.0           NaN
Depreciation And Amortization                    3874000000.0           NaN
Depreciation                                     3874000000.0  3549000000.0
Operating Gains Losses                             44000000.0           NaN
Net Income From Continuing Operations           20081000000.0           NaN

In [30]:
# see `Ticker.get_income_stmt()` for more options

In [31]:
msft.major_holders

Breakdown                          Value
insidersPercentHeld              0.00050
institutionsPercentHeld          0.73551
institutionsFloatPercentHeld     0.73588
institutionsCount             6859.00000

In [32]:
msft.institutional_holders

,Date Reported,Holder,pctHeld,Shares,Value
0,2023-06-30,Vanguard Group Inc,0.0879,653247546,222456919314
1,2023-06-30,Blackrock Inc.,0.0722,536245027,182612881494
2,2023-06-30,State Street Corporation,0.0395,293614078,99987338122
3,2023-06-30,"FMR, LLC",0.0283,210111250,71551285075
4,2023-06-30,Price (T.Rowe) Associates Inc,0.0215,159904219,54453782738
5,2023-06-30,"Geode Capital Management, LLC",0.0199,148129470,50444009713
6,2023-06-30,Morgan Stanley,0.0166,123498322,42056118573
7,2023-06-30,JP Morgan Chase & Company,0.0152,113024837,38489477991
8,2022-12-31,Norges Bank Investment Management,0.0116,86316926,20700525193
9,2023-06-30,Capital World Investors,0.0115,85507261,29118642660

In [33]:
msft.mutualfund_holders

,Date Reported,Holder,pctHeld,Shares,Value
0,2023-06-30,Vanguard Total Stock Market Index Fund,0.0312,231883087,78965466446
1,2023-06-30,Vanguard 500 Index Fund,0.0238,177034936,60287477105
2,2023-08-31,Fidelity 500 Index Fund,0.0115,85181943,27919233637
3,2023-09-30,SPDR S&P 500 ETF Trust,0.0112,83514381,26369665800
4,2023-09-30,iShares Core S&P 500 ETF,0.0095,70264910,22186145332
5,2023-06-30,Vanguard Growth Index Fund,0.0085,63262454,21543396085
6,2023-08-31,"Invesco ETF Tr-Invesco QQQ Tr, Series 1 ETF",0.0079,58757680,19258417196
7,2023-06-30,Vanguard Institutional Index Fund-Institutiona...,0.0068,50756950,17284771753
8,2023-08-31,Vanguard Information Technology Index Fund,0.0053,39119308,12821744390
9,2023-09-30,Growth Fund Of America Inc,0.0053,39310503,12412291322

In [34]:
msft.insider_transactions

,Shares,Value,URL,Text,Insider,Position,Transaction,Start Date,Ownership
0,138,0,,Stock Award(Grant) at price 0.00 per share.,SCHARF CHARLES W,Director,,2024-06-07,D
1,138,0,,Stock Award(Grant) at price 0.00 per share.,STANTON JOHN W.,Director,,2024-06-07,D
2,138,0,,Stock Award(Grant) at price 0.00 per share.,MASON MARK,Director,,2024-06-07,D
3,138,0,,Stock Award(Grant) at price 0.00 per share.,LIST-STOLL TERI L.,Director,,2024-06-07,D
4,16996,0,,Stock Gift at price 0.00 per share.,NADELLA SATYA,Chief Executive Officer,,2024-06-05,I
...,...,...,...,...,...,...,...,...,...
145,166,0,,Stock Award(Grant) at price 0.00 per share.,SCHARF CHARLES W,Director,,2021-09-02,D
146,166,0,,Stock Award(Grant) at price 0.00 per share.,STANTON JOHN W.,Director,,2021-09-02,D
147,166,0,,Stock Award(Grant) at price 0.00 per share.,WARRIOR PADMASREE,Director,,2021-09-02,D
148,166,0,,Stock Award(Grant) at price 0.00 per share.,JOHNSTON HUGH F.,Director,,2021-09-02,D
149,166,0,,Stock Award(Grant) at price 0.00 per share.,WALMSLEY EMMA NATASHA,Director,,2021-09-02,D

In [35]:
msft.insider_purchases

       Insider Purchases Last 6m     Shares  Trans
0                      Purchases    17548.0      5
1                          Sales    58797.0      5
2    Net Shares Purchased (Sold)   -41249.0     10
3      Total Insider Shares Held  3716519.0   <NA>
4  % Net Shares Purchased (Sold)     -0.011   <NA>
5                   % Buy Shares      0.005   <NA>
6                  % Sell Shares      0.016   <NA>

In [36]:
msft.insider_roster_holders

,Name,Position,URL,Most Recent Transaction,Latest Transaction Date,Shares Owned Directly,Position Direct Date,Shares Owned Indirectly,Position Indirect Date
0,ALTHOFF JUDSON,Officer,,Sale,2024-05-23,104949.0,2024-05-23,NaN,NaN
1,HOGAN KATHLEEN T,Officer,,Sale,2024-03-11,159764.0,2024-03-11,NaN,NaN
2,JOHNSTON HUGH F.,Director,,Stock Award(Grant),2024-01-31,7818.0,2024-01-31,NaN,NaN
3,LIST-STOLL TERI L.,Director,,Stock Award(Grant),2024-06-07,1986.0,2024-06-07,NaN,NaN
4,MASON MARK,Director,,Stock Award(Grant),2024-06-07,714.0,2024-06-07,NaN,NaN
5,NADELLA SATYA,Chief Executive Officer,,Stock Gift,2024-06-05,NaN,NaT,818327.0,1.717546e+09
6,NUMOTO TAKESHI,Officer,,Sale,2024-06-03,47011.0,2024-06-03,NaN,NaN
7,SCHARF CHARLES W,Director,,Stock Award(Grant),2024-06-07,44456.0,2024-06-07,NaN,NaN
8,SMITH BRADFORD LEE,President,,Sale,2024-02-05,570826.0,2024-02-05,NaN,NaN
9,STANTON JOHN W.,Director,,Stock Award(Grant),2024-06-07,85187.0,2024-06-07,NaN,NaN

In [38]:
msft.sustainability

                                                                           esgScores
maxAge                                                                         86400
totalEsg                                                                       15.06
environmentScore                                                                1.46
socialScore                                                                     7.53
governanceScore                                                                 6.07
ratingYear                                                                      2023
ratingMonth                                                                        9
highestControversy                                                               3.0
peerCount                                                                        105
esgPerformance                                                            UNDER_PERF
peerGroup                                                        Software & Services
relatedControversy                                              [Customer Incidents]
peerEsgScorePerformance            {'min': 9.84, 'avg': 18.17809523809525, 'max':...
peerGovernancePerformance          {'min': 3.47, 'avg': 6.753495145631067, 'max':...
peerSocialPerformance              {'min': 4.61, 'avg': 8.862038834951454, 'max':...
peerEnvironmentPerformance         {'min': 0.07, 'avg': 2.5702912621359224, 'max'...
peerHighestControversyPerformance  {'min': 0.0, 'avg': 1.5333333333333334, 'max':...
percentile                                                                     11.36
environmentPercentile                                                           None
socialPercentile                                                                None
governancePercentile                                                            None
adult                                                                          False
alcoholic                                                                      False
animalTesting                                                                  False
catholic                                                                       False
controversialWeapons                                                           False
smallArms                                                                      False
furLeather                                                                     False
gambling                                                                       False
gmo                                                                            False
militaryContract                                                               False
nuclear                                                                        False
pesticides                                                                     False
palmOil                                                                        False
coal                                                                           False
tobacco                                                                        False

In [39]:
# show recommendations
msft.recommendations

  period  strongBuy  buy  hold  sell  strongSell
0     0m         14   13     6     0           1
1    -1m         22   33     2     0           0
2    -2m         23   33     3     0           0
3    -3m         20   27     6     0           0

In [40]:
msft.recommendations_summary

  period  strongBuy  buy  hold  sell  strongSell
0     0m         14   13     6     0           1
1    -1m         22   33     2     0           0
2    -2m         23   33     3     0           0
3    -3m         20   27     6     0           0

In [41]:
msft.upgrades_downgrades

                               Firm        ToGrade   FromGrade Action
GradeDate
2024-07-31 16:46:05  Morgan Stanley     Overweight  Overweight   main
2024-07-31 16:20:50         Wedbush     Outperform  Outperform   reit
2024-07-31 15:46:47             UBS            Buy         Buy   main
2024-07-31 14:39:26     RBC Capital     Outperform  Outperform   reit
2024-07-31 11:59:54     Wells Fargo     Overweight  Overweight   main
...                             ...            ...         ...    ...
2012-04-20 10:18:00   Deutsche Bank            Buy               main
2012-04-03 15:53:00             UBS            Buy               main
2012-03-22 11:03:00  Morgan Stanley     Overweight               main
2012-03-19 18:00:00  Hilliard Lyons  Long-Term Buy               main
2012-03-16 12:19:00  Argus Research            Buy        Hold     up

[708 rows x 4 columns]

In [42]:
msft.earnings_dates

                           EPS Estimate  Reported EPS  Surprise(%)
Earnings Date
2025-07-28 16:00:00-04:00           NaN           NaN          NaN
2025-04-23 16:00:00-04:00           NaN           NaN          NaN
2025-01-28 16:00:00-05:00           NaN           NaN          NaN
2024-10-22 06:00:00-04:00          3.09           NaN          NaN
2024-07-30 16:00:00-04:00          2.93          2.95       0.0055
2024-04-25 16:00:00-04:00          2.82          2.94       0.0432
2024-01-30 16:00:00-05:00          2.78          2.93       0.0534
2023-10-24 16:00:00-04:00          2.65          2.99       0.1270
2023-07-25 16:00:00-04:00          2.55          2.69       0.0549
2023-04-25 16:00:00-04:00          2.23          2.45       0.0981
2023-01-24 16:00:00-05:00          2.29          2.32       0.0109
2022-10-25 16:00:00-04:00          2.30          2.35       0.0205

In [43]:
# show options expirations
msft.options

('2024-08-09',
 '2024-08-16',
 '2024-08-23',
 '2024-08-30',
 '2024-09-06',
 '2024-09-13',
 '2024-09-20',
 '2024-10-18',
 '2024-11-15',
 '2024-12-20',
 '2025-01-17',
 '2025-03-21',
 '2025-06-20',
 '2025-09-19',
 '2025-12-19',
 '2026-01-16',
 '2026-06-18',
 '2026-12-18')

In [45]:
# show news
msft.news

8

In [50]:
# get option chain for specific expiration
msft.option_chain('2024-08-23')

Options(calls=         contractSymbol             lastTradeDate  strike  lastPrice     bid  \
0   MSFT240823C00230000 2024-08-02 19:13:55+00:00   230.0     176.73  172.35
1   MSFT240823C00270000 2024-07-16 14:02:16+00:00   270.0     181.80  132.45
2   MSFT240823C00300000 2024-07-31 19:55:00+00:00   300.0     118.65  102.50
3   MSFT240823C00305000 2024-08-01 18:08:32+00:00   305.0     110.27   97.50
4   MSFT240823C00320000 2024-08-02 17:46:29+00:00   320.0      86.62   82.60
5   MSFT240823C00350000 2024-08-07 13:59:29+00:00   350.0      59.65   53.05
6   MSFT240823C00355000 2024-08-08 14:16:10+00:00   355.0      50.21   48.20
7   MSFT240823C00365000 2024-08-07 17:27:23+00:00   365.0      38.66   37.20
8   MSFT240823C00370000 2024-08-08 19:59:53+00:00   370.0      34.70   33.00
9   MSFT240823C00375000 2024-08-08 13:30:03+00:00   375.0      30.10   27.90
10  MSFT240823C00380000 2024-08-08 15:15:10+00:00   380.0      25.68   25.15
11  MSFT240823C00385000 2024-08-08 14:08:22+00:00   385.0      22.10   20.85
12  MSFT240823C00390000 2024-08-08 19:59:31+00:00   390.0      17.30   16.95
13  MSFT240823C00395000 2024-08-08 19:03:52+00:00   395.0      13.10   13.30
14  MSFT240823C00400000 2024-08-08 19:59:38+00:00   400.0      10.55   10.00
15  MSFT240823C00405000 2024-08-08 19:39:14+00:00   405.0       7.10    7.25
16  MSFT240823C00410000 2024-08-08 19:48:28+00:00   410.0       5.30    5.00
17  MSFT240823C00415000 2024-08-08 19:59:38+00:00   415.0       3.50    3.25
18  MSFT240823C00420000 2024-08-08 19:59:09+00:00   420.0       2.05    1.97
19  MSFT240823C00425000 2024-08-08 19:59:48+00:00   425.0       1.32    1.19
20  MSFT240823C00430000 2024-08-08 19:37:52+00:00   430.0       0.75    0.68
21  MSFT240823C00435000 2024-08-08 19:42:41+00:00   435.0       0.46    0.43
22  MSFT240823C00440000 2024-08-08 19:30:59+00:00   440.0       0.32    0.30
23  MSFT240823C00445000 2024-08-08 19:44:47+00:00   445.0       0.20    0.18
24  MSFT240823C00450000 2024-08-08 19:43:56+00:00   450.0       0.14    0.10
25  MSFT240823C00455000 2024-08-08 19:36:57+00:00   455.0       0.11    0.10
26  MSFT240823C00460000 2024-08-08 18:56:29+00:00   460.0       0.09    0.07
27  MSFT240823C00465000 2024-08-08 17:29:44+00:00   465.0       0.05    0.05
28  MSFT240823C00470000 2024-08-08 19:33:53+00:00   470.0       0.03    0.02
29  MSFT240823C00475000 2024-08-08 15:03:58+00:00   475.0       0.05    0.01
30  MSFT240823C00480000 2024-08-07 13:41:56+00:00   480.0       0.05    0.01
31  MSFT240823C00485000 2024-08-08 17:43:38+00:00   485.0       0.03    0.01
32  MSFT240823C00490000 2024-08-07 19:06:18+00:00   490.0       0.04    0.01
33  MSFT240823C00495000 2024-08-07 18:12:08+00:00   495.0       0.03    0.00
34  MSFT240823C00500000 2024-08-08 18:15:37+00:00   500.0       0.03    0.01
35  MSFT240823C00505000 2024-08-08 16:31:57+00:00   505.0       0.03    0.00
36  MSFT240823C00510000 2024-08-07 15:43:10+00:00   510.0       0.01    0.00
37  MSFT240823C00515000 2024-08-06 15:42:39+00:00   515.0       0.05    0.00
38  MSFT240823C00520000 2024-08-02 19:01:24+00:00   520.0       0.02    0.00
39  MSFT240823C00525000 2024-08-02 19:01:25+00:00   525.0       0.02    0.00
40  MSFT240823C00530000 2024-08-05 17:39:00+00:00   530.0       0.02    0.00
41  MSFT240823C00535000 2024-08-05 17:45:26+00:00   535.0       0.01    0.00
42  MSFT240823C00540000 2024-07-31 16:01:20+00:00   540.0       0.02    0.00
43  MSFT240823C00560000 2024-07-30 19:19:58+00:00   560.0       0.05    0.00

       ask    change  percentChange  volume  openInterest  impliedVolatility  \
0   174.65  0.000000       0.000000     3.0             5           1.408206
1   134.35  0.000000       0.000000     1.0             0           1.024907
2   103.75  0.000000       0.000000     1.0             3           0.726077
3    98.80  0.000000       0.000000     NaN             3           0.696780
4    83.95  0.000000       0.000000     1.0             1           0.617191
5    54.95  0.000000       0.000000     1.0             9           0.562749
6    50.50  2.090000       4.343309     6.0            15           0.555546
7    39.90  0.000000       0.000000    10.0             9           0.432257
8    35.20  1.889999       5.760437     2.0           110           0.406256
9    30.60 -1.850000      -5.790298     2.0             4           0.381842
10   25.70  2.260000       9.649873     2.0            25           0.339972
11   21.40  1.950001       9.677423     1.0            17           0.320563
12   17.40  1.799999      11.612898    24.0           112           0.304878
13   13.75  0.180000       1.393191   274.0           102           0.291694
14   10.45  1.480001      16.317535  1265.0          3406           0.278572
15    7.55  0.500000       7.575757   309.0           353           0.265022
16    5.30 -0.100000      -1.851850   319.0           382           0.257332
17    3.45  0.300000       9.374999   225.0           476           0.247200
18    2.15 -0.150000      -6.818186   342.0          1061           0.240364
19    1.32 -0.120000      -8.333333   328.0           886           0.237801
20    0.81 -0.180000     -19.354840   190.0          1241           0.238533
21    0.51 -0.220000     -32.352940    84.0           570           0.242195
22    0.34 -0.110000     -25.581400   131.0          1901           0.249031
23    0.26 -0.120000     -37.499996   609.0           692           0.261726
24    0.18 -0.080000     -36.363636   185.0          1859           0.269539
25    0.13 -0.040000     -26.666668   136.0           830           0.278328
26    0.12 -0.020000     -18.181814    54.0           709           0.295905
27    0.08 -0.040000     -44.444447    26.0          2454           0.300300
28    0.09 -0.050000     -62.499996    43.0           763           0.324226
29    0.08  0.010000      25.000004     9.0           621           0.338874
30    0.07  0.000000       0.000000     1.0           278           0.351569
31    0.05 -0.020000     -40.000004     1.0           217           0.355475
32    0.06  0.000000       0.000000     1.0           273           0.380866
33    0.06  0.000000       0.000000     6.0           101           0.398444
34    0.03  0.020000     200.000000    19.0           557           0.386725
35    0.05  0.000000       0.000000     5.0            76           0.423834
36    0.01  0.000000       0.000000     1.0             0           0.378912
37    0.05  0.000000       0.000000     1.0            25           0.455084
38    0.04  0.000000       0.000000    15.0            57           0.460943
39    0.04  0.000000       0.000000    10.0            21           0.476568
40    0.04  0.000000       0.000000    15.0            39           0.492193
41    0.04  0.000000       0.000000     5.0            62           0.505864
42    0.01  0.000000       0.000000     8.0            40           0.460943
43    0.05  0.000000       0.000000    10.0            13           0.554692

    inTheMoney contractSize currency
0         True      REGULAR      USD
1         True      REGULAR      USD
2         True      REGULAR      USD
3         True      REGULAR      USD
4         True      REGULAR      USD
5         True      REGULAR      USD
6         True      REGULAR      USD
7         True      REGULAR      USD
8         True      REGULAR      USD
9         True      REGULAR      USD
10        True      REGULAR      USD
11        True      REGULAR      USD
12        True      REGULAR      USD
13        True      REGULAR      USD
14        True      REGULAR      USD
15       False      REGULAR      USD
16       False      REGULAR      USD
17       False      REGULAR      USD
18       False      REGULAR      USD
19       False      REGULAR      USD
20       False      REGULAR      USD
21       False      REGULAR      USD
22       False      REGULAR      USD
23       False      REGULAR      USD
24       False      REGULAR      USD
25       False      REGULAR      USD
26       False      REGULAR      USD
27       False      REGULAR      USD
28       False      REGULAR      USD
29       False      REGULAR      USD
30       False      REGULAR      USD
31       False      REGULAR      USD
32       False      REGULAR      USD
33       False      REGULAR      USD
34       False      REGULAR      USD
35       False      REGULAR      USD
36       False      REGULAR      USD
37       False      REGULAR      USD
38       False      REGULAR      USD
39       False      REGULAR      USD
40       False      REGULAR      USD
41       False      REGULAR      USD
42       False      REGULAR      USD
43       False      REGULAR      USD  , puts=         contractSymbol             lastTradeDate  strike  lastPrice     bid  \
0   MSFT240823P00230000 2024-08-06 14:45:12+00:00   230.0       0.04    0.00
1   MSFT240823P00270000 2024-08-05 17:46:06+00:00   270.0       0.23    0.00
2   MSFT240823P00280000 2024-08-07 19:53:31+00:00   280.0       0.05    0.01
3   MSFT240823P00290000 2024-08-08 19:07:12+00:00   290.0       0.10    0.04
4   MSFT240823P00295000 2024-08-06 13:43:08+00:00   295.0       0.45    0.05
5   MSFT240823P00300000 2024-08-08 18:08:17+00:00   300.0       0.10    0.07
6   MSFT240823P00305000 2024-08-08 17:42:47+00:00   305.0       0.11    0.10
7   MSFT240823P00310000 2024-08-08 16:41:22+00:00   310.0       0.17    0.11
8   MSFT240823P00315000 2024-08-08 15:56:59+00:00   315.0       0.20    0.15
9   MSFT240823P00320000 2024-08-08 18:12:38+00:00   320.0       0.21    0.19
10  MSFT240823P00325000 2024-08-08 16:42:04+00:00   325.0       0.31    0.23
11  MSFT240823P00330000 2024-08-08 14:50:49+00:00   330.0       0.32    0.28
12  MSFT240823P00335000 2024-08-08 14:44:15+00:00   335.0       0.37    0.33
13  MSFT240823P00340000 2024-08-08 18:25:16+00:00   340.0       0.44    0.40
14  MSFT240823P00345000 2024-08-08 19:39:58+00:00   345.0       0.59    0.49
15  MSFT240823P00350000 2024-08-08 19:18:50+00:00   350.0       0.68    0.60
16  MSFT240823P00355000 2024-08-08 16:37:49+00:00   355.0       0.95    0.73
17  MSFT240823P00360000 2024-08-08 19:57:42+00:00   360.0       1.00    0.89
18  MSFT240823P00365000 2024-08-08 19:59:06+00:00   365.0       1.18    1.11
19  MSFT240823P00370000 2024-08-08 19:58:37+00:00   370.0       1.54    1.39
20  MSFT240823P00375000 2024-08-08 19:45:12+00:00   375.0       1.90    1.78
21  MSFT240823P00380000 2024-08-08 19:33:07+00:00   380.0       2.76    2.31
22  MSFT240823P00385000 2024-08-08 19:37:20+00:00   385.0       3.82    3.00
23  MSFT240823P00390000 2024-08-08 19:55:38+00:00   390.0       4.35    4.00
24  MSFT240823P00395000 2024-08-08 18:37:06+00:00   395.0       4.95    5.30
25  MSFT240823P00400000 2024-08-08 19:56:25+00:00   400.0       7.60    7.05
26  MSFT240823P00405000 2024-08-08 19:36:54+00:00   405.0       9.74    9.20
27  MSFT240823P00410000 2024-08-08 19:47:43+00:00   410.0      12.65   11.95
28  MSFT240823P00415000 2024-08-08 19:38:01+00:00   415.0      16.15   15.20
29  MSFT240823P00420000 2024-08-08 19:32:15+00:00   420.0      20.90   19.00
30  MSFT240823P00425000 2024-08-08 19:55:07+00:00   425.0      23.50   22.95
31  MSFT240823P00430000 2024-08-08 15:09:04+00:00   430.0      28.30   27.40
32  MSFT240823P00435000 2024-08-08 19:10:22+00:00   435.0      32.80   32.15
33  MSFT240823P00440000 2024-08-08 18:51:22+00:00   440.0      38.59   37.00
34  MSFT240823P00445000 2024-08-07 18:33:14+00:00   445.0      43.61   41.90
35  MSFT240823P00450000 2024-08-08 18:51:22+00:00   450.0      47.34   46.85
36  MSFT240823P00455000 2024-08-08 17:13:35+00:00   455.0      52.63   51.85
37  MSFT240823P00460000 2024-08-08 18:59:44+00:00   460.0      57.49   56.80
38  MSFT240823P00465000 2024-08-08 17:13:35+00:00   465.0      62.73   60.85
39  MSFT240823P00470000 2024-08-05 13:31:22+00:00   470.0      82.70   66.80
40  MSFT240823P00475000 2024-07-18 15:40:24+00:00   475.0      40.05   70.80
41  MSFT240823P00480000 2024-07-31 13:38:59+00:00   480.0      64.17   76.80
42  MSFT240823P00485000 2024-08-01 13:34:35+00:00   485.0      66.00   81.75
43  MSFT240823P00490000 2024-07-31 14:01:35+00:00   490.0      71.22   85.75
44  MSFT240823P00500000 2024-07-25 19:38:05+00:00   500.0      79.47   96.80
45  MSFT240823P00505000 2024-07-31 17:22:16+00:00   505.0      88.08  100.75
46  MSFT240823P00530000 2024-07-25 19:38:06+00:00   530.0     109.48  125.85
47  MSFT240823P00535000 2024-07-25 19:38:06+00:00   535.0     114.50  131.75

       ask    change  percentChange  volume  openInterest  impliedVolatility  \
0     0.06  0.000000       0.000000       1             0           0.945313
1     0.08  0.000000       0.000000       1             3           0.710940
2     0.10  0.000000       0.000000       1             8           0.673831
3     0.11 -0.060000     -37.499996       5            23           0.634769
4     0.13  0.000000       0.000000      22            61           0.617191
5     0.15 -0.100000     -50.000000      10           150           0.601566
6     0.17 -0.990000     -90.000000      15            42           0.585942
7     0.20 -0.100000     -37.037040     100            50           0.565434
8     0.22  0.030000      17.647058      13            73           0.546880
9     0.26 -0.230000     -52.272728      10            73           0.530278
10    0.30 -0.190000     -38.000000      20            56           0.511235
11    0.35  0.040000      14.285711       3            74           0.500982
12    0.42 -0.220000     -37.288130      30           172           0.483404
13    0.49 -0.060000     -12.000000      10            49           0.462652
14    0.58 -0.300000     -33.707867     113           261           0.442877
15    0.69  0.000000       0.000000      15           131           0.423346
16    0.83 -0.160000     -14.414416       4           114           0.404059
17    1.01 -0.500000     -33.333332      52           187           0.385382
18    1.22 -1.040000     -46.846850      21           198           0.365363
19    1.54 -0.630000     -29.032263     247           254           0.348883
20    1.91 -1.150000     -37.704918      32           492           0.329963
21    2.48 -1.620000     -36.986305      79             0           0.315437
22    3.20 -1.500000     -28.195494      70           702           0.299934
23    4.30 -2.150000     -33.076927      77           697           0.290229
24    5.65 -3.800000     -43.428574      35           650           0.278328
25    7.40 -2.100000     -21.649483     161           832           0.267463
26    9.65 -3.660000     -27.313433      68             0           0.258613
27   12.40 -3.250000     -20.440252      79           511           0.250618
28   15.70 -4.240000     -20.794506      36           742           0.245064
29   19.50 -3.380001     -13.920927     144          1474           0.242195
30   24.85 -3.729999     -13.698125      41           542           0.297920
31   28.80 -2.470001      -8.027303      10           360           0.282478
32   34.50 -2.680000      -7.553552       8           318           0.355597
33   39.35 -2.979999      -7.168630     197           366           0.381720
34   44.25 -2.700001      -5.830275      16           230           0.408575
35   49.20  4.750000      11.152853       3           133           0.437017
36   53.15  5.020001      10.544004       6           133           0.384894
37   58.15 -2.799999      -4.644218       8           103           0.411383
38   63.15 -4.200001      -6.275214       1            35           0.437017
39   68.10  0.000000       0.000000       3            28           0.456548
40   73.10  0.000000       0.000000       4             0           0.480962
41   78.10  0.000000       0.000000      10             0           0.504888
42   83.10  0.000000       0.000000       1             0           0.528569
43   88.10  0.000000       0.000000       1             0           0.551518
44   98.10  0.000000       0.000000       2             2           0.596195
45  103.10  0.000000       0.000000       3             1           0.618168
46  128.05  0.000000       0.000000       2             0           0.714114
47  133.70  0.000000       0.000000       1             0           0.670169

    inTheMoney contractSize currency
0        False      REGULAR      USD
1        False      REGULAR      USD
2        False      REGULAR      USD
3        False      REGULAR      USD
4        False      REGULAR      USD
5        False      REGULAR      USD
6        False      REGULAR      USD
7        False      REGULAR      USD
8        False      REGULAR      USD
9        False      REGULAR      USD
10       False      REGULAR      USD
11       False      REGULAR      USD
12       False      REGULAR      USD
13       False      REGULAR      USD
14       False      REGULAR      USD
15       False      REGULAR      USD
16       False      REGULAR      USD
17       False      REGULAR      USD
18       False      REGULAR      USD
19       False      REGULAR      USD
20       False      REGULAR      USD
21       False      REGULAR      USD
22       False      REGULAR      USD
23       False      REGULAR      USD
24       False      REGULAR      USD
25       False      REGULAR      USD
26        True      REGULAR      USD
27        True      REGULAR      USD
28        True      REGULAR      USD
29        True      REGULAR      USD
30        True      REGULAR      USD
31        True      REGULAR      USD
32        True      REGULAR      USD
33        True      REGULAR      USD
34        True      REGULAR      USD
35        True      REGULAR      USD
36        True      REGULAR      USD
37        True      REGULAR      USD
38        True      REGULAR      USD
39        True      REGULAR      USD
40        True      REGULAR      USD
41        True      REGULAR      USD
42        True      REGULAR      USD
43        True      REGULAR      USD
44        True      REGULAR      USD
45        True      REGULAR      USD
46        True      REGULAR      USD

In [54]:
# multiple tickers

tickers = yf.Tickers('msft aapl goog')

# access each ticker using (example)
tickers.tickers['MSFT'].info
tickers.tickers['AAPL'].history(period="1mo")
tickers.tickers['GOOG'].actions

                           Dividends  Stock Splits
Date
2014-03-27 00:00:00-04:00        0.0      2.002000
2015-04-27 00:00:00-04:00        0.0      1.002746
2022-07-18 00:00:00-04:00        0.0     20.000000
2024-06-10 00:00:00-04:00        0.2      0.000000